add aurora tools to mth5
kujaku11/mth5 pull request #229
Opened 2024-07-31 01:28 UTC by kujaku11

Add some aurora tools that have a broader application

- [ ] add `mth5.tables.channel_summary.to_run_summary()`
  - [ ] add `mth5.MTH5.run_summary` convenience method

2024-08-23 00:38 UTC, kkappler requested changes
Nice additions.  Run_summary is going to be very useful in future!

This looks ready to merge after verifying check tests.yaml is supposed to be on `anna` branch.

Minor Comments:
- Most changes shown in github were just black re-formatting.  It would be good to sync our precommit.yaml files so these changes are less common in future.
- I added some minor changes (improvements) to `make_mth5_from_ascii.py` on `patches` branch. Perhaps these could be be melded in?  But if not, I'll meld this with patches so no problem.  I guess, whichever hits main first will be the reference.
- I tested run_summary in a separate application and it seems to behave as expected.  Yay!

2024-08-23 00:38 UTC, kkappler commented on .github/workflows/tests.yml
Should the mt_metadata branch be changed back to `main` before merging ?

2024-08-23 00:38 UTC, kkappler commented on mth5/data/make_mth5_from_asc.py
might be good to meld this against `patches` branch before merge

2024-08-25 19:01 UTC, kujaku11 reviewed
Changes are good and pass tests

2024-08-25 19:06 UTC, merged